Feature - Add Data Authorization Handler
OpenSourcePolitics/decidim-cd44 pull request #64
Opened 2022-11-09 09:51 UTC by AyakorK

Hello ! I'm doing this pull request to suggest you the addition of a Data Authorization Handler when the user wants to create a new proposal.

This authorization handler will ask you to fill in your name, your firstname, your phone with a mandatory aspect, and a structure if the users has one to fill in.

To activate it you should go into the participatory processes and add this authorization handler to your Proposals settings.

If you have some requests to me or if some things bother you don't mind asking me !

(n.b. There are two files that are changed that replace "expect" to "allow" but actually it was some easy changes to make the linter not break but that are not actually linked to the feature.)

2022-11-09 14:42 UTC, Quentinchampenois requested changes

2022-11-09 14:42 UTC, Quentinchampenois commented on spec/system/data_authorization_spec.rb
> +      puts "AAAAAA"
Can you remove `puts "AAAAAA"`

2022-11-09 14:42 UTC, Quentinchampenois commented on spec/system/data_authorization_spec.rb
> +      puts phone.match(/\A0[1-9]\d{8}\z/)
Can you turn this print to an assertion ?

2022-11-09 15:26 UTC, AyakorK commented
> @AyakorK why didn't you use an external module to create your AH?

If you mean that you wanted it to be created in an external module to be use on other instances, the fact that it didn't seem it was for multiple uses, I've decided to do it only on CD44 and not on an external module.

2022-11-10 13:51 UTC, armandfardeau requested changes
Hello @AyakorK Can you check the validators please?

2022-11-10 13:51 UTC, armandfardeau commented on app/services/decidim/data_authorization_handler.rb
> +    validates :firstname, presence: true, length: { minimum: 1 }
```suggestion
    validates :lastname, presence: true
    validates :firstname, presence: true
```

2022-11-14 12:22 UTC, armandfardeau approved these changes

2022-11-15 15:15 UTC, OuardaOUBAHRI approved these changes
All good ! Thank you 🙏

2022-11-15 17:13 UTC, merged