Develop
OpenSourcePolitics/decidim-cd44 pull request #68
Opened 2022-11-22 14:35 UTC by eliegaboriau

Bump master

 - Add timer to check if the sign up form is completed too fast
 - Add gem paper ballots
 - Add friendly sign up and update question_captcha
 - Add Data authorization handler
 - Bump to 0.26.4

2022-11-23 09:00 UTC, AyakorK approved these changes

2022-11-28 14:59 UTC, armandfardeau requested changes

2022-11-28 14:59 UTC, armandfardeau commented on app/controllers/decidim/devise/registrations_controller.rb
> +# frozen_string_literal: true
Don't override by monkeypatching

2022-11-28 15:00 UTC, armandfardeau commented
Hi, thanks for your contribution, I've changed this P.R. status to draft, feel free to undraft when tests passes.

2023-01-23 08:42 UTC, closed without merging