FIX - Fontface not interpreted || Folders reassignment
OpenSourcePolitics/decidim-cd44 pull request #78
Opened 2022-12-16 09:24 UTC by AyakorK

Hello ! I'm doing this pull request, in cooperation with @Quentinchampenois, to fix CD44's fonts

When we updated the instance to 0.26.0, some file changes weren't done correctly, so files and folder were not at the place they were supposed to be. So in facts, with multiple corrections on _fontface.scss file, and some moves of folders into app/packs, we were able to fix the fonts that are now well used on our page.

In addition of that we updated some versions of our gems that were not following the 0.26.4 of our instance and were still stuck to 0.26.1 and deleted some useless imports into our scss files.

🚨 We also had to fix webpack because it wasn't following greatly changes we made and caused some more issues

Don't mind bothering me if you have some questions about it, and if some changes does not look good for you, you can for sure ask for few changes.

2022-12-16 10:45 UTC, armandfardeau requested changes
Hi @AyakorK and thanks for your contribution.
I've switched this P.R. in draft mode, please un-draft only if CI is all green, then ask for review.

2022-12-19 17:10 UTC, Quentinchampenois approved these changes

2022-12-20 11:28 UTC, Quentinchampenois commented on app/packs/stylesheets/decidim/decidim_application.scss
> +@import "email/email-custom";
@paulinebessoles we check if css is applied or not, with last commit we are duplicating the email-custom scss file in the pack

2022-12-21 14:17 UTC, Quentinchampenois approved these changes

2022-12-23 09:12 UTC, paulinebessoles approved these changes

2022-12-23 09:12 UTC, merged