[FIX] - Metadata duplication task
OpenSourcePolitics/decidim-cd44 pull request #94
Opened 2023-02-27 17:01 UTC by AyakorK

## Description

This PR is made with the objective to fix one task that didn't work at all before this. 
The initial objective of this task was to duplicate metadata from authorization handlers using a rake task.
It seemed that failing tests weren't notified coreclty and that the feature didn't work for a while and even probably since its creation. This PR was made in cooperation with @Quentinchampenois 

## What changed ?

- We separated the task in two ways
  - One task file to execute it
  - A class that will contain what we wanted about this feature
- We clarified and add some new specs

2023-02-28 10:28 UTC, Quentinchampenois commented
We should separate your PR subject (metadata duplication task) and other fixes (head.html.erb / locales fixes / CI / etc).

What I suggest is to create new branch with commits before `e2b0ff0` and then change target of this PR on the newly created branch

2023-02-28 12:21 UTC, Quentinchampenois requested changes
We must refactor the existing to simplify maintainance

2023-02-28 12:21 UTC, Quentinchampenois commented on lib/decidim/duplicates_metadata.rb
> +    def update_authorized_users
`updated_authorized_users` and `update_metadata` are not easy to read, we should consider refactor to keep it simple

2023-02-28 12:21 UTC, Quentinchampenois commented on spec/lib/decidim/duplicates_metadata_spec.rb
> +  context "when user has no metadata" do
It is easier if we use `shared_examples`  and `it_behaves_like` clausure to simplify reading and file

2023-03-02 09:47 UTC, armandfardeau approved these changes

2023-03-02 09:48 UTC, merged